services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    restart: unless-stopped
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - jenkins-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    depends_on:
      - jenkins-docker
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client
      - ./secrets:/var/jenkins_home/secrets
    environment:
      AVA_OPTS: "-Djava.awt.headless=true"
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    user: root
    
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-certs:

networks:
  jenkins: